In [52]:
import requests
from bs4 import BeautifulSoup
from urllib.request import urlopen
import pandas as pd
from html_table_parser import parser_functions as parser
import numpy as np

In [99]:
url="http://www.seoulmetro.co.kr/kr/page.do?menuIdx=366#none"
request=requests.get(url)
soup=BeautifulSoup(request.text,"html.parser")

#### [soup.select('span[class="Second_Tag"]')[0] select로 불러오는 법](https://blog.yonghyeon.com/44)

In [99]:
#밑에 이걸 쓰면 user-select에 따라 달라지지 않는 페이지에서 원하는 표 추출하기 힘듦 
#data=soup.find("div",{"class":"tbl-box1 m-top20"})

#빈 리스트 하나 생성해서 데이터 프레임 담아주기
dfs=[]
for i in range(0,9):
#find랑 select랑 비슷한데 이거 쓰면 리스트 숫자만 바꿔서 전체 호선 출력 가능
    data=soup.select('div[class="tbl-box1 m-top20"]')[i]

    table=parser.make2d(data)
    df=pd.DataFrame(data=table[1:],columns=table[0])
    df['호선']=str(i+1)+"호선" #호선 칼럼 달아주기
    dfs.append(df)

#### [여러 개 데이터 테이블 for 문 참고페이지](https://hashcode.co.kr/questions/10662/%EB%B0%98%EB%B3%B5%EB%AC%B8%EC%9D%84-%EC%82%AC%EC%9A%A9%ED%95%B4%EC%84%9C-%EB%8D%B0%EC%9D%B4%ED%84%B0%ED%94%84%EB%A0%88%EC%9E%84%EC%9D%84-%EC%97%AC%EB%9F%AC%EA%B0%9C-%EB%A7%8C%EB%93%9C%EB%8A%94-%EB%B0%A9%EB%B2%95%EC%9D%B4-%EC%96%B4%EB%96%BB%EA%B2%8C-%EB%90%A0%EA%B9%8C%EC%9A%94)

#### [concat 참고 페이지](https://yganalyst.github.io/data_handling/Pd_12/#1-2-%EC%8B%9C%EB%A6%AC%EC%A6%88%EB%A5%BC-%EB%8D%B0%EC%9D%B4%ED%84%B0%ED%94%84%EB%A0%88%EC%9E%84%EC%97%90-%EB%B6%99%EC%9D%B4%EA%B8%B0)

In [104]:
fini_df=pd.concat(dfs[0:9]) #파이썬에서 :ㅁ는  (ㅁ-1)까지
fini_df

        역명 엘리베이터 에스컬레이터 수평보행기 휠체어리프트 이동식안전발판 전동휠체어급속충전기 장애인 화장실 음성유도기   호선
0      서울역     4      5            1       1                  1    33  1호선
1      시청역     3      3                    1                  1    32  1호선
2      종각역     4      2                    1          1       1    38  1호선
3    종로3가역     3      4                    1          1       1    48  1호선
4    종로5가역     3                           1                  1    32  1호선
..     ...   ...    ...   ...    ...     ...        ...     ...   ...  ...
8     송파나루     5      6                                       1    28  9호선
9     한성백제     3     12                                       1    23  9호선
10   올림픽공원     3     14                                       2    34  9호선
11    둔촌오륜     3      8                                       1    19  9호선
12  중앙보훈병원     5     10                                       1    31  9호선

[296 rows x 10 columns]

In [148]:
#fini_df.reset_index(inplace=True) #인덱스 재설정
#fini_df.drop(columns=['index'], inplace=True) #인덱스 칼럼 삭제
fini_df

         역명 엘리베이터 에스컬레이터 수평보행기 휠체어리프트 이동식안전발판 전동휠체어급속충전기 장애인 화장실 음성유도기   호선
0       서울역     4      5            1       1                  1    33  1호선
1       시청역     3      3                    1                  1    32  1호선
2       종각역     4      2                    1          1       1    38  1호선
3     종로3가역     3      4                    1          1       1    48  1호선
4     종로5가역     3                           1                  1    32  1호선
..      ...   ...    ...   ...    ...     ...        ...     ...   ...  ...
291    송파나루     5      6                                       1    28  9호선
292    한성백제     3     12                                       1    23  9호선
293   올림픽공원     3     14                                       2    34  9호선
294    둔촌오륜     3      8                                       1    19  9호선
295  중앙보훈병원     5     10                                       1    31  9호선

[296 rows x 10 columns]

In [208]:
fini_df.to_csv("서울교통공사 지하철 배려시설.csv",index=False,encoding = 'cp949') #csv로 내보내기